# Generated by Django 3.2.6 on 2021-08-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_alter_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
